### ISSUE TITLE
v1.0.1 seems not compatible with 0.9.0

### ISSUE THREAD

**Issue by iredmail** [ChartsCSS/charts.css#108]
Same html code works fine in v0.9.0 but not 1.0.1.
In v1.0.1, chart looks like a background image and other html data (not part of chart) floats on it.

BTW, i use Bootstrap v5.

**Comment by ramiy** [comment]
@iredmail 

The new version has some breaking changes. I'm currently rewriting the official docs at ChartsCSS.org which will include a migration guide from 0.x to 1.x.

You can also share your HTML here (or a share a codepen link), and I'll try to help you fix it, or refer you to the relevant  docs.

**Comment by eea76** [comment]
@ramiy i'm looking forward to this migration guide. many of my charts broke with 1.0. hopefully it will just be a matter of changing some class names in the html? attached two screenshots as an example

![Screen Shot 2023-10-07 at 9 24 31 AM](https://github.com/ChartsCSS/charts.css/assets/6385099/01ad2a73-9fdc-455f-ac49-e7ab55f667ed)
![Screen Shot 2023-10-07 at 9 25 40 AM](https://github.com/ChartsCSS/charts.css/assets/6385099/b561fac6-b118-4f1c-ac3f-6199d733d58b)

**Comment by ramiy** [comment]
To fix broken charts, go back to 0.9.0 version.

Replace:
`<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/charts.css/dist/charts.min.css">`

With:
`<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/charts.css@0.9.0/dist/charts.min.css">`

**Comment by ramiy** [comment]
See the migration guide at https://chartscss.org/docs/migrate-to-v1/
