### ISSUE TITLE
Can we add labels in both x / y axis?

### ISSUE THREAD

**Issue by tomyo** [ChartsCSS/charts.css#12]
For looking at the docs, is not clear to me I can add lables in both axes, all examples use at most only one, giving the feeling this feature is missing.

I would even recommend to having an example with "all the complementary info you can add".

Library looking good!

**Comment by ramiy** [comment]
@tomyo Currently the framework doesn't supports labels on both axes.

**Comment by eea76** [comment]
Hoping this can be supported in the future. I just discovered this framework yesterday and I'm thrilled with how easy it is to implement, use, and manipulate, but I'd really love to have Y-axis labels on column c harts at some point. Every example in the docs made me go "ok but what about the Y-axis?

**Comment by ramiy** [comment]
@eea76 I know, it should be simple to add Y-axis labels but I'm still debating how to implement this feature. Y-labels are in my roadmap.

**Comment by mrspence** [comment]
@ramiy Slightly off-topic, but is your roadmap public? Don't worry, not looking to hold you to your own roadmap haha, just curious :)

**Comment by ramiy** [comment]
The [roadmap](https://chartscss.org/development/roadmap/) is **public** but **not updated**.

**Comment by ramiy** [comment]
@tomyo @eea76 see https://chartscss.org/components/axes/#axis-title
