### ISSUE TITLE
Stacked bar charts - would be so great

### ISSUE THREAD

**Issue by JohnCClarke** [ChartsCSS/charts.css#14]
This is a great library. Data in a table is so much more usable than Google charts that we are currently using.

Would it be easy to add stacked bar charts? I.e. each bar is the stacked "sum" of multiple components? Then we could switch.

**Comment by ramiy** [comment]
@JohnCClarke The framework supports [stacking](https://chartscss.org/components/stacked/).

Check the **Stacked Bars** documentation https://chartscss.org/components/stacked/#stacked-bars

**Comment by JohnCClarke** [comment]
OMG! - Thanks for pointing that out. Somehow I just didn't spot them.

Marvellous!
