### ISSUE TITLE
A charts.css binding for Python is available

### ISSUE THREAD

**Issue by rayluo** [ChartsCSS/charts.css#46]
Hi @ramiy , thank you (and Lana) very much for your great work on the Charts.css! The charts look so nice, and I love the [Charts.css's approach](https://chartscss.org/docs/#how-it-works) so much, that I can't help but create a [binding](https://en.wikipedia.org/wiki/Language_binding) for Charts.css for it to be used in Python. To honor the heritage, the binding is named - what else - [charts.css.py](https://github.com/rayluo/charts.css.py), currently supporting most of the basic functionalities of charts.css, demonstrated in [its doc](https://rayluo.github.io/charts.css.py/).

It would be nice if you can add a "language binding" section in Charts.css 's doc and link to the charts.css.py project. This way you/we can better serve a segment of audience who are familiar with Python but less fluent in css.

**Comment by ramiy** [comment]
Thank you @rayluo !!

Added `charts.css.py` to [awesome Charts.css resources and libraries](https://github.com/ChartsCSS/awesome).

**Comment by rayluo** [comment]
Thanks for your quick action, @ramiy ! Appreciate that.

It is also my first time to be aware of the existence of that ["awesome Charts.css resources and libraries" page](https://github.com/ChartsCSS/awesome), and the other alumni on that list. :-) So my follow-up question is, do you plan to somehow expose it and make it more discoverable? Currently I'm only aware of the main Charts.css site https://chartscss.org/ and its docs https://chartscss.org/docs/, yet neither of those main site mentions the "awesome resources".

**Comment by ramiy** [comment]
[Awesome Charts.css](https://github.com/ChartsCSS/awesome) is a new repo, created only two weeks ago. I didn't exposed it to the public (yet). First I want to add few resources for theme and plugin developers.

When the list will be big enough I will expose it and make it more discoverable. You will see a link from the main site - https://chartscss.org/

In any case, thank you for your contribution to the project, if you have more ideas how to integrate Charts.css in other frameworks and libraries I'll love to promote them in [Awesome Charts.css](https://github.com/ChartsCSS/awesome) repo.

(also, don't forget to start the main repo - it help immensely)

**Comment by rayluo** [comment]
I think an extra "Resources" section appended at the existing main https://chartscss.org/ and/or https://chartscss.org/docs/ would be a lightweight yet practical approach to provide immediate visibility for those new frameworks. And a flourishing eco-system would help Charts.css itself, too.

Not until that "Resources section" become larger and large, we would need to create a separated repo. Just my 2 cents.
